//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp4P.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db4PEntities : DbContext
    {
        public Db4PEntities()
            : base("name=Db4PEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Endereco> Enderecos { get; set; }
        public virtual DbSet<FuncionarioEndereco> FuncionarioEnderecos { get; set; }
        public virtual DbSet<Funcionario> Funcionarios { get; set; }
    }
}
